name: rucio-webui
version: 34.0.0
apiVersion: v1
description: A Helm chart to deploy the new Rucio Webui
keywords:
  - data-management
  - science
home: https://rucio.cern.ch/
sources:
  - https://github.com/rucio/webui
maintainers:
  - name: Rucio development team
    email: rucio-dev@cern.ch
