name: rucio-daemons
version: 1.30.10
apiVersion: v1
description: A Helm chart to deploy daemons for Rucio
keywords:
  - data-management
  - science
home: https://rucio.cern.ch/
sources:
  - https://github.com/rucio/rucio
maintainers:
  - name: Rucio development team
    email: rucio-dev@cern.ch
