{{- define "rucio-daemons.conveyor-deployement" }}
{{- $app_label := printf "%s-%s" (include "rucio.name" .) .rucio_daemon }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "rucio.fullname" . }}.config.{{ .rucio_daemon }}
  labels:
    app: {{ $app_label }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{- $common_config := .Values.config | default dict | mustToPrettyJson | b64enc }}
  {{- $component_config := .component_values.config | default dict | mustToPrettyJson | b64enc }}
  component.json: {{ $component_config | quote }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .rucio_daemon }}
  labels:
    app: {{ $app_label }}
    app-group: {{ template "rucio.name" . }}
    chart: {{ template "rucio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .component_count }}
  selector:
    matchLabels:
      app: {{ $app_label }}
      release: {{ .Release.Name }}
  strategy:
    type: {{ .Values.strategy.type }}
{{- if eq .Values.strategy.type "RollingUpdate" }}
    {{- with .Values.strategy.rollingUpdate }}
    rollingUpdate:
{{ toYaml . | trim | indent 6 }}
    {{- end }}
{{- end }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  template:
    metadata:
      labels:
        app: {{ $app_label }}
        app-group: {{ template "rucio.name" . }}
        release: {{ .Release.Name }}
        rucio-daemon: {{ .rucio_daemon }}
    {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
      annotations:
        checksum/config: {{ print "%s%s" .common_config .component_config | sha1sum }}
    {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .component_values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
    spec:
    {{- if .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
    {{- end }}
      volumes:
      - name: config-common
        secret:
          secretName: {{ template "rucio.fullname" . }}.config.common
      - name: config-component
        secret:
          secretName: {{ template "rucio.fullname" . }}.config.{{ .rucio_daemon }}
    {{- if .Values.useDeprecatedImplicitSecrets }}
      - name: proxy-volume
        secret:
          secretName: {{ .Release.Name }}-rucio-x509up
      - name: ca-volume
        secret:
          secretName: {{ .Release.Name }}-rucio-ca-bundle
    {{- end }}
      {{- range $collection := tuple (coalesce .component_values.secretMounts .Values.secretMounts .Values.additionalSecrets) .component_values.extraSecretMounts }}
      {{- range $key, $val := $collection }}
      - name: {{ kindIs "int" $key | ternary (coalesce $val.volumeName $val.secretName $val.secretFullName) $key }}
        secret:
          secretName: {{ coalesce $val.secretFullName (printf "%s-%s" $.Release.Name $val.secretName) }}
      {{- end}}
      {{- end}}
      {{- range $key, $val := .Values.persistentVolumes }}
      - name: {{ $key }}
        persistentVolumeClaim:
          claimName: {{ $val.name }}
      {{- end}}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ coalesce (.component_values.image | default dict).tag .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          {{- if .Values.useDeprecatedImplicitSecrets }}
            - name: proxy-volume
              mountPath: /opt/proxy
            - name: ca-volume
              mountPath: /opt/certs
          {{- end }}
            - name: config-common
              mountPath: /opt/rucio/etc/conf.d/10_common.json
              subPath: common.json
            - name: config-component
              mountPath: /opt/rucio/etc/conf.d/20_component.json
              subPath: component.json
          {{- range $collection := tuple (coalesce .component_values.secretMounts .Values.secretMounts .Values.additionalSecrets) .component_values.extraSecretMounts }}
          {{- range $key, $val := $collection }}
            - name: {{ kindIs "int" $key | ternary (coalesce $val.volumeName $val.secretName $val.secretFullName) $key }}
              mountPath: {{ $val.mountPath }}
              {{- if $val.subPath }}
              subPath: "{{ $val.subPath }}"
              {{- end }}
          {{- end}}
          {{- end}}
          {{- range $key, $val := .Values.persistentVolumes }}
            - name: {{ $key }}
              mountPath: {{ $val.mountPath }}
          {{- end}}
          ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
          env:
            {{- range $key1, $val1 := .Values.optional_config }}
            - name: {{ $key1 | upper }}
              value: "{{ $val1  }}"
            {{- end}}
            - name: RUCIO_OVERRIDE_CONFIGS
              value: "/opt/rucio/etc/conf.d/"
            - name: RUCIO_DAEMON
              value: "{{ .rucio_daemon }}"
            - name: RUCIO_DAEMON_ARGS
              value: "{{ .daemon_args }}"
{{- with .component_values.resources }}
          resources:
{{ toYaml . | trim | indent 12 }}
{{ end }}
{{- with .component_values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .component_values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .component_values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
{{ end }}


{{- define "rucio-daemons.conveyor-finisher-daemon-args" }}
{{- if .threads }} --total-threads {{ .threads }}{{ end }} {{- if .dbBulk }} --db-bulk {{ .dbBulk }}{{ end }} {{- if .bulk }} --bulk {{ .bulk }}{{ end }} {{- if .sleepTime }} --sleep-time {{ .sleepTime }}{{ end }} {{- if .activities }} --activities {{ .activities }}{{ end }}
{{- end }}
{{- if gt .Values.conveyorFinisherCount 0.0 -}}
{{- $args := dict "Values" .Values "Release" .Release "Chart" .Chart "Capabilities" .Capabilities }}
{{- $args = set $args "rucio_daemon" "conveyor-finisher" }}
{{- $args = set $args "component_values" .Values.conveyorFinisher }}
{{- $args = set $args "component_count" .Values.conveyorFinisherCount }}
{{- $args = set $args "daemon_args" (include "rucio-daemons.conveyor-finisher-daemon-args" .Values.conveyorFinisher) }}
{{- include "rucio-daemons.conveyor-deployement" $args }}
{{ end }}

{{- define "rucio-daemons.conveyor-poller-daemon-args" }}
{{- if .threads }} --total-threads {{ .threads }}{{ end }} {{ if .dbBulk }} --db-bulk {{ .dbBulk }}{{ end }} {{- if .ftsBulk }} --fts-bulk {{ .ftsBulk }}{{ end }} {{- if .sleepTime }} --sleep-time {{ .sleepTime }}{{ end }} {{- if .activities }} --activities {{ .activities }}{{ end }} {{- if .olderThan }} --older-than {{ .olderThan }}{{ end }} {{- if .activitiesShare }} --activities-share {{ .activitiesShare }}{{ end }}
{{- end }}
{{- if gt .Values.conveyorPollerCount 0.0 -}}
{{- $args := dict "Values" .Values "Release" .Release "Chart" .Chart "Capabilities" .Capabilities }}
{{- $args = set $args "rucio_daemon" "conveyor-poller" }}
{{- $args = set $args "component_values" .Values.conveyorPoller}}
{{- $args = set $args "component_count" .Values.conveyorPollerCount }}
{{- $args = set $args "daemon_args" (include "rucio-daemons.conveyor-poller-daemon-args" .Values.conveyorPoller) }}
{{- include "rucio-daemons.conveyor-deployement" $args }}
{{ end }}

{{- define "rucio-daemons.conveyor-preparer-daemon-args" }}
{{- if .threads }} --threads {{ .threads }}{{ end }} {{ if .bulk }} --bulk {{ .bulk }}{{ end }} {{- if .sleepTime }} --sleep-time {{ .sleepTime }}{{ end }}
{{- end }}
{{- if gt .Values.conveyorPreparerCount 0.0 -}}
{{- $args := dict "Values" .Values "Release" .Release "Chart" .Chart "Capabilities" .Capabilities }}
{{- $args = set $args "rucio_daemon" "conveyor-preparer" }}
{{- $args = set $args "component_values" .Values.conveyorPreparer}}
{{- $args = set $args "component_count" .Values.conveyorPreparerCount }}
{{- $args = set $args "daemon_args" (include "rucio-daemons.conveyor-preparer-daemon-args" .Values.conveyorPreparer) }}
{{- include "rucio-daemons.conveyor-deployement" $args }}
{{ end }}

{{- define "rucio-daemons.conveyor-receiver-daemon-args" }}
{{- if .threads }} --total-threads {{ .threads }}{{ end }} {{- if .fullMode }} --full-mode{{ end }}
{{- end }}
{{- if gt .Values.conveyorReceiverCount 0.0 -}}
{{- $args := dict "Values" .Values "Release" .Release "Chart" .Chart "Capabilities" .Capabilities }}
{{- $args = set $args "rucio_daemon" "conveyor-receiver" }}
{{- $args = set $args "component_values" .Values.conveyorReceiver}}
{{- $args = set $args "component_count" .Values.conveyorReceiverCount }}
{{- $args = set $args "daemon_args" (include "rucio-daemons.conveyor-receiver-daemon-args" .Values.conveyorReceiver) }}
{{- include "rucio-daemons.conveyor-deployement" $args }}
{{ end }}

{{- define "rucio-daemons.conveyor-stager-daemon-args" }}
{{- if .threads }} --total-threads {{ .threads }}{{ end }} {{- if .bulk }} --bulk {{ .bulk }}{{ end }} {{- if .bulk }} --bulk {{ .bulk }}{{ end }} {{- if .sleepTime }} --sleep-time {{ .sleepTime }}{{ end }} {{- if .activities }} --activities {{ .activities }}{{ end }}
{{- end }}
{{- if gt .Values.conveyorStagerCount 0.0 -}}
{{- $args := dict "Values" .Values "Release" .Release "Chart" .Chart "Capabilities" .Capabilities }}
{{- $args = set $args "rucio_daemon" "conveyor-stager" }}
{{- $args = set $args "component_values" .Values.conveyorStager}}
{{- $args = set $args "component_count" .Values.conveyorStagerCount }}
{{- $args = set $args "daemon_args" (include "rucio-daemons.conveyor-stager-daemon-args" .Values.conveyorStager) }}
{{- include "rucio-daemons.conveyor-deployement" $args }}
{{ end }}

{{- define "rucio-daemons.conveyor-submitter-daemon-args" }}
{{- if .threads }} --total-threads {{ .threads }}{{ end }} {{- if .bulk }} --bulk {{ .bulk }}{{ end }} {{- if .groupBulk }} --group-bulk {{ .groupBulk }}{{ end}}{{- if .groupPolicy }} --group-policy {{ .groupPolicy }}{{ end }} {{- if .mock }} --mock {{ .mock }}{{ end }} {{- if .sourceStrategy }} --source-strategy {{ .sourceStrategy }}{{ end }} {{- if .excludeRses }} --exclude-rses {{ .excludeRses }}{{ end}} {{- if .includeRses }} --include-rses {{ .includeRses }}{{ end}} {{- if .rses }} --rses {{ .rses }}{{ end}} {{- if .sleepTime }} --sleep-time {{ .sleepTime }}{{ end}} {{- if .activities }} --activities {{ .activities }}{{ end}} {{- if .excludeActivities }} --exclude-activities {{ .excludeActivities }}{{ end}} {{- if .maxSources }} --max-sources {{ .maxSources }}{{end }} {{- if .ignoreAvailability }} --ignore-availability {{ end }} {{- if .retryOtherFts }} --retry-other-fts {{ end}} {{- if kindIs "float64" .archiveTimeout }}  --archive-timeout-override {{ .archiveTimeout }}{{ end}}
{{- end }}
{{- if gt .Values.conveyorTransferSubmitterCount 0.0 -}}
{{- $args := dict "Values" .Values "Release" .Release "Chart" .Chart "Capabilities" .Capabilities }}
{{- $args = set $args "rucio_daemon" "conveyor-submitter" }}
{{- $args = set $args "component_values" .Values.conveyorTransferSubmitter}}
{{- $args = set $args "component_count" .Values.conveyorTransferSubmitterCount }}
{{- $args = set $args "daemon_args" (include "rucio-daemons.conveyor-submitter-daemon-args" .Values.conveyorTransferSubmitter) }}
{{- include "rucio-daemons.conveyor-deployement" $args }}
{{ end }}

{{- define "rucio-daemons.conveyor-throttler-daemon-args" }}
{{- if .sleepTime }} --sleep-time {{ .sleepTime }}{{ end }}
{{- end }}
{{- if gt .Values.conveyorThrottlerCount 0.0 -}}
{{- $args := dict "Values" .Values "Release" .Release "Chart" .Chart "Capabilities" .Capabilities }}
{{- $args = set $args "rucio_daemon" "conveyor-throttler" }}
{{- $args = set $args "component_values" .Values.conveyorThrottler}}
{{- $args = set $args "component_count" .Values.conveyorThrottlerCount }}
{{- $args = set $args "daemon_args" (include "rucio-daemons.conveyor-throttler-daemon-args" .Values.conveyorThrottler) }}
{{- include "rucio-daemons.conveyor-deployement" $args }}
{{ end }}
