{{- if gt .Values.traceReplicaCount 0.0 -}}
{{- if .Values.traceIngress.enabled -}}
{{- $fullName := include "rucio.fullname" . -}}
{{- $ingressPath := .Values.traceIngress.path -}}
{{- $kubeApiVersion := include "rucio.ingress.apiVersion" . -}}
apiVersion: {{ $kubeApiVersion }}
kind: Ingress
metadata:
  name: {{ $fullName }}-trace
  labels:
    app: {{ template "rucio.name" . }}-trace
    chart: {{ template "rucio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.traceIngress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.traceIngress.tls }}
  tls:
  {{- range .Values.traceIngress.tls }}
    - hosts:
      {{- range $.Values.ingress.hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.traceIngress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
    {{- if eq $kubeApiVersion "networking.k8s.io/v1" }}
              service:
                name: {{ $fullName }}-trace
                port:
                  number: {{ $.Values.traceService.port }}
            pathType: Prefix
    {{- else }}
              serviceName: {{ $fullName }}-trace
              servicePort: {{ $.Values.traceService.port }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}