name: rucio-ui
version: 1.27.0
apiVersion: v1
description: A Helm chart to deploy webui servers for Rucio
keywords:
  - data-management
  - science
home: https://rucio.cern.ch/
sources:
  - https://github.com/rucio/rucio
maintainers:
  - name: Rucio development team
    email: rucio-dev@cern.ch

