name: rucio-server
version: 1.28.1
apiVersion: v1
description: A Helm chart to deploy servers for Rucio
keywords:
  - data-management
  - science
home: https://rucio.cern.ch/
sources:
  - https://github.com/rucio/rucio
maintainers:
  - name: Rucio development team
    email: rucio-dev@cern.ch
